FROM ubuntu:16.04
MAINTAINER Amy

# RUN apt-get update
# RUN apt-get upgrade -y
# RUN apt-get install -y software-properties-common
# RUN add-apt-repository ppa:webupd8team/java -y
# RUN apt-get install -y python3

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y python3
RUN apt-get install -y g++